// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RevenueAITask.Models
{
    [Table("AccountType")]
    public partial class AccountType
    {
        public AccountType()
        {
            Accounts = new HashSet<Account>();
        }

        [Key]
        [Column("AccountTypeID")]
        public int AccountTypeId { get; set; }
        [Required]
        [StringLength(50)]
        public string AccountTypeDesc { get; set; }

        [InverseProperty(nameof(Account.AccountType))]
        public virtual ICollection<Account> Accounts { get; set; }
    }
}