// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RevenueAITask.Models
{
    [Table("CardType")]
    public partial class CardType
    {
        public CardType()
        {
            Cards = new HashSet<Card>();
        }

        [Key]
        [Column("CardTypeID")]
        public int CardTypeId { get; set; }
        [Required]
        [Column("CardType")]
        [StringLength(50)]
        public string CardType1 { get; set; }

        [InverseProperty(nameof(Card.CardType))]
        public virtual ICollection<Card> Cards { get; set; }
    }
}