// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RevenueAITask.Models
{
    [Table("CardState")]
    public partial class CardState
    {
        public CardState()
        {
            Cards = new HashSet<Card>();
        }

        [Key]
        [Column("StateID")]
        public int StateId { get; set; }
        [Required]
        [StringLength(50)]
        public string StateDescription { get; set; }

        [InverseProperty(nameof(Card.State))]
        public virtual ICollection<Card> Cards { get; set; }
    }
}