// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RevenueAITask.Models
{
    [Table("Card")]
    public partial class Card
    {
        public Card()
        {
            Transactions = new HashSet<Transaction>();
        }

        [Key]
        [StringLength(16, MinimumLength = 16, ErrorMessage = "Card length should be 16 characters")]

        public string CardNumber { get; set; }
        [Column("valid")]
        [StringLength(3)]
        [DataType(DataType.Password)]

        public string Valid { get; set; }
        [Column("StateID")]
        public int StateId { get; set; }
        [Column("CardTypeID")]
        public int CardTypeId { get; set; }
        [Column("currencyID")]
        public int CurrencyId { get; set; }
        [Column("UserID")]
        public int UserId { get; set; }

        [ForeignKey(nameof(CardTypeId))]
        [InverseProperty("Cards")]
        public virtual CardType CardType { get; set; }
        [ForeignKey(nameof(CurrencyId))]
        [InverseProperty("Cards")]
        public virtual Currency Currency { get; set; }
        [ForeignKey(nameof(StateId))]
        [InverseProperty(nameof(CardState.Cards))]
        public virtual CardState State { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("Cards")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(Transaction.CardNumberNavigation))]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}