// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RevenueAITask.Models
{
    [Table("PasswordRecoveryHistory")]
    public partial class PasswordRecoveryHistory
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("UserID")]
        public int UserId { get; set; }
        [StringLength(50)]
        public string RecoveryInitialPassword { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SendDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ExpireDate { get; set; }
        [Column("isUsed")]
        [StringLength(1)]
        public string IsUsed { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("PasswordRecoveryHistories")]
        public virtual User User { get; set; }
    }
}