// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RevenueAITask.Models
{
    [Table("Transaction")]
    public partial class Transaction
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        public double? Amount { get; set; }
        [Column("TransactionTypeID")]
        public int TransactionTypeId { get; set; }
        [Required]
        [StringLength(16)]
        public string CardNumber { get; set; }
        [Column("VendorID")]
        public int VendorId { get; set; }

        [ForeignKey(nameof(CardNumber))]
        [InverseProperty(nameof(Card.Transactions))]
        public virtual Card CardNumberNavigation { get; set; }
        [ForeignKey(nameof(TransactionTypeId))]
        [InverseProperty("Transactions")]
        public virtual TransactionType TransactionType { get; set; }
        [ForeignKey(nameof(VendorId))]
        [InverseProperty("Transactions")]
        public virtual Vendor Vendor { get; set; }
    }
}