// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RevenueAITask.Models
{
    [Table("UserType")]
    public partial class UserType
    {
        public UserType()
        {
            Users = new HashSet<User>();
        }

        [Key]
        [Column("UserTypeID")]
        public int UserTypeId { get; set; }
        [Required]
        [StringLength(10)]
        public string UserTypeDesc { get; set; }

        [InverseProperty(nameof(User.UserType))]
        public virtual ICollection<User> Users { get; set; }
    }
}