// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RevenueAITask.Models
{
    [Table("User")]
    public partial class User
    {
        public User()
        {
            Accounts = new HashSet<Account>();
            Cards = new HashSet<Card>();
            PasswordRecoveryHistories = new HashSet<PasswordRecoveryHistory>();
        }

        [Key]
        [Column("UserID")]
        public int UserId { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string UserName { get; set; }
        [Column("UserTypeID")]
        public int UserTypeId { get; set; }
        [StringLength(50)]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastLoginTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastPasswordChangeDate { get; set; }

        [ForeignKey(nameof(UserTypeId))]
        [InverseProperty("Users")]
        public virtual UserType UserType { get; set; }

        [InverseProperty(nameof(Account.User))]
        public virtual ICollection<Account> Accounts { get; set; }

        [InverseProperty(nameof(Card.User))]
        public virtual ICollection<Card> Cards { get; set; }
        [InverseProperty(nameof(PasswordRecoveryHistory.User))]
        public virtual ICollection<PasswordRecoveryHistory> PasswordRecoveryHistories { get; set; }
    }
}