// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RevenueAITask.Models
{
    [Table("Vendor")]
    public partial class Vendor
    {
        public Vendor()
        {
            Transactions = new HashSet<Transaction>();
        }

        [Key]
        [Column("VendorID")]
        public int VendorId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Address { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [Column("mail")]
        [StringLength(50)]
        public string Mail { get; set; }

        [InverseProperty(nameof(Transaction.Vendor))]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}